ARG ubi_version
ARG node_version

FROM registry.access.redhat.com/ubi${ubi_version}/nodejs-${node_version}

ENV CNB_STACK_ID=com.redhat.stacks.ubi${ubi_version}-nodejs-${node_version}
ENV CNB_USER_ID=1001
ENV CNB_GROUP_ID=0

