FROM registry.access.redhat.com/ubi8/nodejs-14
ENV CNB_USER_ID=1001
ENV CNB_GROUP_ID=1001
ENV CNB_STACK_ID="com.redhat.stacks.ubi8-nodejs-14"
ENV CNB_STACK_DESC="ubi nodejs run image base"
LABEL io.buildpacks.stack.id="com.redhat.stacks.ubi8-nodejs-14"
